version: '3.8'
services:
  elixir_agent:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/apps/a2a_agent_web
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=dev
    depends_on:
      nats:
        condition: service_healthy
  python_agent:
    build:
      context: ./agents/python_agents/minimal_a2a_agent
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      nats:
        condition: service_healthy
  nats:
    image: nats:2.10-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "4222"]
      interval: 2s
      timeout: 2s
      retries: 15
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - elixir_agent
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
