"""Workspace builder for BLACKICE 3.0.

Creates the structured workspace for a run, including directories
for repo, tests, docs, decisions, and logs.
"""

from __future__ import annotations

import os
import shutil
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from blackice.primitives.types import Edition, RunId


@dataclass
class WorkspaceConfig:
    """Configuration for workspace creation."""

    base_path: Path = field(default_factory=lambda: Path.home() / ".blackice" / "workspaces")
    create_git: bool = True
    include_readme: bool = True
    include_gitignore: bool = True


@dataclass
class WorkspaceInfo:
    """Information about a created workspace."""

    path: Path
    run_id: RunId
    created_at: datetime
    directories: dict[str, Path]


class WorkspaceBuilder:
    """Builder for creating run workspaces.

    A workspace contains the structured output of a BLACKICE run:
    - repo/: Generated source code
    - tests/: Generated tests
    - docs/: Generated documentation
    - decisions/: Architectural decision records
    - logs/: Run logs and event log
    - artifacts/: Build artifacts
    """

    def __init__(self, config: WorkspaceConfig | None = None) -> None:
        self.config = config or WorkspaceConfig()

    def create(
        self,
        run_id: RunId,
        vision: str,
        edition: Edition = Edition.LITE,
        **metadata: Any,
    ) -> WorkspaceInfo:
        """Create a new workspace for a run.

        Args:
            run_id: Run identifier
            vision: Vision description (for README)
            edition: BLACKICE edition
            **metadata: Additional metadata

        Returns:
            WorkspaceInfo with paths and metadata
        """
        # Create workspace directory
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        workspace_name = f"{timestamp}_{str(run_id)[:8]}"
        workspace_path = self.config.base_path / workspace_name
        workspace_path.mkdir(parents=True, exist_ok=True)

        # Create subdirectories
        directories = self._create_directories(workspace_path)

        # Create initial files
        if self.config.include_readme:
            self._create_readme(workspace_path, vision, run_id, edition)

        if self.config.include_gitignore:
            self._create_gitignore(workspace_path)

        if self.config.create_git:
            self._init_git(workspace_path)

        # Create run metadata file
        self._create_metadata(workspace_path, run_id, vision, edition, metadata)

        return WorkspaceInfo(
            path=workspace_path,
            run_id=run_id,
            created_at=datetime.now(timezone.utc),
            directories=directories,
        )

    def _create_directories(self, workspace_path: Path) -> dict[str, Path]:
        """Create workspace subdirectories."""
        dirs = {
            "repo": workspace_path / "repo",
            "tests": workspace_path / "tests",
            "docs": workspace_path / "docs",
            "decisions": workspace_path / "decisions",
            "logs": workspace_path / "logs",
            "artifacts": workspace_path / "artifacts",
            "checkpoints": workspace_path / ".blackice" / "checkpoints",
        }

        for name, path in dirs.items():
            path.mkdir(parents=True, exist_ok=True)
            # Create .gitkeep for empty dirs
            if name not in ("checkpoints",):
                (path / ".gitkeep").touch()

        return dirs

    def _create_readme(
        self,
        workspace_path: Path,
        vision: str,
        run_id: RunId,
        edition: Edition,
    ) -> None:
        """Create workspace README."""
        readme = f"""# BLACKICE Run Workspace

**Run ID**: {run_id}
**Edition**: {edition.value}
**Created**: {datetime.now(timezone.utc).isoformat()}

## Vision

{vision}

## Directory Structure

- `repo/` - Generated source code
- `tests/` - Generated tests
- `docs/` - Generated documentation
- `decisions/` - Architectural decision records
- `logs/` - Run logs and event log
- `artifacts/` - Build artifacts

## Generated by BLACKICE 3.0

This workspace was generated by [BLACKICE](https://blackice.dev), an agentic
software factory that converts vision to working software.
"""
        (workspace_path / "README.md").write_text(readme)

    def _create_gitignore(self, workspace_path: Path) -> None:
        """Create .gitignore file."""
        gitignore = """# BLACKICE workspace gitignore

# Checkpoints and internal state
.blackice/

# Logs (optional: comment out to track logs)
logs/*.log

# Build artifacts
artifacts/

# OS files
.DS_Store
Thumbs.db

# Editor files
.vscode/
.idea/
*.swp
*.swo

# Python
__pycache__/
*.py[cod]
.venv/
venv/
.env

# Node
node_modules/
npm-debug.log

# Generated files that shouldn't be committed
*.tmp
*.bak
"""
        (workspace_path / ".gitignore").write_text(gitignore)

    def _init_git(self, workspace_path: Path) -> None:
        """Initialize git repository."""
        import subprocess

        try:
            subprocess.run(
                ["git", "init"],
                cwd=workspace_path,
                capture_output=True,
                check=True,
            )
            subprocess.run(
                ["git", "add", "."],
                cwd=workspace_path,
                capture_output=True,
                check=True,
            )
            subprocess.run(
                ["git", "commit", "-m", "Initial commit by BLACKICE"],
                cwd=workspace_path,
                capture_output=True,
                check=True,
            )
        except (subprocess.CalledProcessError, FileNotFoundError):
            # Git not available or failed, continue without
            pass

    def _create_metadata(
        self,
        workspace_path: Path,
        run_id: RunId,
        vision: str,
        edition: Edition,
        metadata: dict[str, Any],
    ) -> None:
        """Create run metadata file."""
        import json

        meta = {
            "run_id": str(run_id),
            "edition": edition.value,
            "vision": vision,
            "created_at": datetime.now(timezone.utc).isoformat(),
            "blackice_version": "3.0.0",
            **metadata,
        }

        meta_dir = workspace_path / ".blackice"
        meta_dir.mkdir(parents=True, exist_ok=True)
        (meta_dir / "run.json").write_text(json.dumps(meta, indent=2))

    def cleanup(self, workspace_path: Path, keep_logs: bool = True) -> None:
        """Clean up a workspace.

        Args:
            workspace_path: Path to workspace
            keep_logs: Whether to preserve logs directory
        """
        if not workspace_path.exists():
            return

        if keep_logs:
            # Move logs to a temp location
            logs_path = workspace_path / "logs"
            if logs_path.exists():
                temp_logs = workspace_path.parent / f"logs_{workspace_path.name}"
                shutil.move(str(logs_path), str(temp_logs))

        # Remove workspace
        shutil.rmtree(workspace_path)

        if keep_logs:
            # Restore logs
            if temp_logs.exists():
                temp_logs.rename(workspace_path / "logs")

    def list_workspaces(self) -> list[WorkspaceInfo]:
        """List all workspaces.

        Returns:
            List of WorkspaceInfo for each workspace
        """
        workspaces: list[WorkspaceInfo] = []

        if not self.config.base_path.exists():
            return workspaces

        for path in self.config.base_path.iterdir():
            if path.is_dir():
                meta_file = path / ".blackice" / "run.json"
                if meta_file.exists():
                    import json

                    meta = json.loads(meta_file.read_text())
                    from uuid import UUID

                    workspaces.append(
                        WorkspaceInfo(
                            path=path,
                            run_id=RunId(UUID(meta["run_id"])),
                            created_at=datetime.fromisoformat(meta["created_at"]),
                            directories={
                                "repo": path / "repo",
                                "tests": path / "tests",
                                "docs": path / "docs",
                            },
                        )
                    )

        return sorted(workspaces, key=lambda w: w.created_at, reverse=True)
