name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      nats:
        image: nats:2.10-alpine
        ports:
          - 4222:4222
    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.16'
          otp-version: '26.2'
      - name: Install Elixir deps
        run: |
          cd apps/a2a_agent_web
          mix deps.get
      - name: Run Elixir tests
        run: |
          cd apps/a2a_agent_web
          mix test
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Python deps
        run: |
          cd agents/python_agents/minimal_a2a_agent
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      - name: Run Python tests
        run: |
          cd agents/python_agents/minimal_a2a_agent
          source .venv/bin/activate
          pytest || true
