name: ACE Benchmark

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest
    env:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev] sentence-transformers faiss-cpu

      - name: Prepare benchmark output directory
        run: mkdir -p results/benchmark

      - name: Baseline run
        run: python scripts/run_benchmark.py benchmarks/finance_subset.jsonl baseline --output results/benchmark/baseline_finance.json

      - name: ACE run
        run: python scripts/run_benchmark.py benchmarks/finance_subset.jsonl ace_full --output results/benchmark/ace_finance.json

      - name: Upload benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: ace-benchmark-results
          path: results/benchmark/*.json
          if-no-files-found: error
